[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Gradient-black-@xxxx@
Comment=A black gradient theme with gradients & rounded corners
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Gradient-black-@xxxx@
Type=X-GNOME-Metatheme
Comment=A black gradient theme with gradients & rounded corners
Encoding=UTF-8
MetacityTheme=Gradient-black
IconTheme=elementary-xfce-dark
CursorTheme=DMZ-Black
ButtonLayout=:minimize,maximize,close
